name: Run Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Instala as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Execute testes unitários
      - name: Run unit tests
        run: npm run test:unit

      # Executa testes E2E
      - name: Run E2E tests
        run: npm run test:e2e
